name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]  # Ensure Node.js version is 14.x or higher

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2  # Ensure you're using the latest setup-node action
      with:
        node-version: ${{ matrix.node-version }}
    - name: Check Node.js version
      run: node --version  # This line prints the version of Node.js being used
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test